export enum ScreenNames {
  GESTURE_HANDLER_TOUCHABLE = "GESTURE_HANDLER_TOUCHABLE",
  REACT_NATIVE_TOUCHABLE = "RN_TOUCHABLE",
  DYNAMIC_CHILDREN = "DYNAMIC_CHILDREN",
  INSTANT_ROOT = "INSTANT_ROOT",
  HOOKS = "HOOKS",
  FLEXIBLE_STYLES = "FLEXIBLE_STYLES",
  BOTTOM_SHEET = "BOTTOM_SHEET",
  MESSENGER = "MESSENGER",
  PORTAL_BEFORE_HOST = "PORTAL_BEFORE_HOST",
  RECYCLING = "RECYCLING",
  INSTAGRAM_FEED = "INSTAGRAM_FEED",
  INSTAGRAM_REELS = "INSTAGRAM_REELS",
  NAVIGATION_LIFECYCLE = "NAVIGATION_LIFECYCLE",
  NAVIGATION_LIFECYCLE_NESTED = "NAVIGATION_LIFECYCLE_NESTED",
  TRAVEL_EXPLORE = "TRAVEL_EXPLORE",
  TRAVEL_DETAILS = "TRAVEL_DETAILS",
  TELEPORTATION_ORDER = "TELEPORTATION_ORDER",
  RICH_TEXT_EDITOR = "RICH_TEXT_EDITOR",
  PERSISTED_PORTAL = "PERSISTED_PORTAL",
  PHOTO_GALLERY = "PHOTO_GALLERY",
  PHOTO_DETAIL = "PHOTO_DETAIL",
  MIRROR = "MIRROR",
}

export enum StackNames {
  EXAMPLES = "EXAMPLES",
  EXAMPLES_STACK = "EXAMPLES_STACK",
}
